stages:
  - build
  - deploy

build-job:
  stage: build
  image: docker:latest
  services:
    - name: "docker:dind"
      alias: docker
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build . -t raidzin/raidzin:latest
    - docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    - docker push -t raidzin/raidzin:latest


deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
