stages:
  - build
  - deploy

build:
  stage: build
  image: docker:latest
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
      - src
      - public
      - pakcage.json
      - bun.lock
      - astro.config.mjs
      - tsconfig.json
      - Dockerfile
  services:
    - name: "docker:dind"
      alias: docker
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build . -t raidzin/raidzin:latest
    - docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    - docker push raidzin/raidzin:latest

deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - apt-get update && apt-get install openssh-client -y
    - eval $(ssh-agent -s)
    - echo "$RAIDZIN_KEY" | tr -d '\r' | ssh-add -
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $RAIDZIN_HOST >> ~/.ssh/known_hosts
  script: -|
    ssh $RAIDZIN_USER@$RAIDZIN_HOST "
    sudo docker compose -f /root/raidzin/docker-compose.yaml pull
    & sudo docker compose -f /root/raidzin/docker-compose.yaml dow
    & sudo docker compose -f /root/raidzin/docker-compose.yaml up -d
    "
